function [inspectionData,inspectionMetadata,status] = virtual_source_adapter(frame,context,configuration)
%VIRTUAL_SOURCE_ADAPTER Map approved virtual imagery/context to generic contracts.

[inspectionData,inspectionMetadata,status] = emptyOutputs();
try
    if ~validConfiguration(configuration) || ...
            ~validContext(context,configuration) || ~validFrame(frame,context)
        return
    end

    inspectionData = struct( ...
        "itemId",context.itemId, ...
        "payloadRef",context.payloadRef, ...
        "modality",uint8(1), ...
        "sourceId",configuration.sourceId, ...
        "sequenceId",context.sequenceId, ...
        "timestamp",context.captureTimestamp, ...
        "schemaVersion",configuration.inspectionDataSchemaVersion);
    inspectionMetadata = struct( ...
        "itemId",context.itemId, ...
        "acquisitionContext",context.acquisitionContextRef, ...
        "calibrationRef",context.cameraCalibrationRef, ...
        "contextSchemaVersion",context.metadataVersion);
    status = struct( ...
        "accepted",true, ...
        "statusCode",uint8(1), ...
        "itemId",context.itemId, ...
        "contextValid",true, ...
        "frameValid",true);
catch
    [inspectionData,inspectionMetadata,status] = emptyOutputs();
end
end

function valid = validConfiguration(value)
required = ["sourceId";"inspectionDataSchemaVersion";"metadataSchemaVersion"; ...
    "adapterVersion";"configurationVersion";"allowedReferenceFrameIds"; ...
    "environmentMinimum";"environmentMaximum"];
valid = isstruct(value) && isscalar(value) && all(isfield(value,required)) && ...
    scalarOfClass(value.sourceId,"uint32",true) && ...
    scalarOfClass(value.inspectionDataSchemaVersion,"uint16",true) && ...
    scalarOfClass(value.metadataSchemaVersion,"uint16",true) && ...
    scalarOfClass(value.adapterVersion,"uint16",true) && ...
    scalarOfClass(value.configurationVersion,"uint16",true) && ...
    isa(value.allowedReferenceFrameIds,"uint16") && ...
    isequal(size(value.allowedReferenceFrameIds),[2 1]) && ...
    all(value.allowedReferenceFrameIds ~= 0) && ...
    isa(value.environmentMinimum,"single") && ...
    isequal(size(value.environmentMinimum),[4 1]) && ...
    isa(value.environmentMaximum,"single") && ...
    isequal(size(value.environmentMaximum),[4 1]) && ...
    all(isfinite(value.environmentMinimum)) && ...
    all(isfinite(value.environmentMaximum)) && ...
    all(value.environmentMinimum < value.environmentMaximum);
end

function valid = validContext(value,configuration)
required = ["itemId";"payloadRef";"acquisitionContextRef"; ...
    "cameraCalibrationRef";"sequenceId";"scenarioId"; ...
    "captureTimestamp";"referenceFrameId";"imageWidth";"imageHeight"; ...
    "channelCount";"projectionType";"position";"orientation"; ...
    "environmentalContext";"sourceVersion";"adapterVersion"; ...
    "scenarioVersion";"metadataVersion";"configurationVersion"];
if ~(isstruct(value) && isscalar(value) && all(isfield(value,required)))
    valid = false;
    return
end

uint32Fields = ["itemId";"payloadRef";"acquisitionContextRef"; ...
    "cameraCalibrationRef";"sequenceId";"scenarioId"];
valid = all(arrayfun(@(name) scalarOfClass(value.(name),"uint32",true),uint32Fields)) && ...
    scalarOfClass(value.captureTimestamp,"uint64",true) && ...
    scalarOfClass(value.referenceFrameId,"uint16",true) && ...
    any(value.referenceFrameId == configuration.allowedReferenceFrameIds) && ...
    scalarOfClass(value.imageWidth,"uint16",true) && ...
    scalarOfClass(value.imageHeight,"uint16",true) && ...
    scalarOfClass(value.channelCount,"uint8",true) && value.channelCount == uint8(3) && ...
    scalarOfClass(value.projectionType,"uint8",true) && ...
    any(value.projectionType == uint8([1 2])) && ...
    isa(value.position,"double") && isequal(size(value.position),[3 1]) && ...
    all(isfinite(value.position)) && ...
    isa(value.orientation,"double") && isequal(size(value.orientation),[4 1]) && ...
    all(isfinite(value.orientation)) && abs(norm(value.orientation)-1) <= 1e-12 && ...
    isa(value.environmentalContext,"single") && ...
    isequal(size(value.environmentalContext),[4 1]) && ...
    all(isfinite(value.environmentalContext)) && ...
    all(value.environmentalContext >= configuration.environmentMinimum) && ...
    all(value.environmentalContext <= configuration.environmentMaximum) && ...
    scalarOfClass(value.sourceVersion,"uint16",true) && ...
    scalarOfClass(value.adapterVersion,"uint16",true) && ...
    value.adapterVersion == configuration.adapterVersion && ...
    scalarOfClass(value.scenarioVersion,"uint16",true) && ...
    scalarOfClass(value.metadataVersion,"uint16",true) && ...
    value.metadataVersion == configuration.metadataSchemaVersion && ...
    scalarOfClass(value.configurationVersion,"uint16",true) && ...
    value.configurationVersion == configuration.configurationVersion;
end

function valid = validFrame(frame,context)
valid = (isa(frame,"uint8") || isa(frame,"uint16") || ...
    isa(frame,"single") || isa(frame,"double")) && ~isempty(frame) && ...
    isreal(frame) && ndims(frame) == 3 && all(isfinite(frame(:))) && ...
    isequal(size(frame),[double(context.imageHeight),double(context.imageWidth),3]);
end

function valid = scalarOfClass(value,className,nonzero)
valid = isa(value,className) && isscalar(value) && isreal(value) && ...
    isfinite(double(value));
if valid && nonzero
    valid = value ~= 0;
end
end

function [data,metadata,status] = emptyOutputs()
data = struct("itemId",uint32(0),"payloadRef",uint32(0), ...
    "modality",uint8(0),"sourceId",uint32(0),"sequenceId",uint32(0), ...
    "timestamp",uint64(0),"schemaVersion",uint16(0));
metadata = struct("itemId",uint32(0),"acquisitionContext",uint32(0), ...
    "calibrationRef",uint32(0),"contextSchemaVersion",uint16(0));
status = struct("accepted",false,"statusCode",uint8(2),"itemId",uint32(0), ...
    "contextValid",false,"frameValid",false);
end
