function valid = validateRiskPolicy(policy)
%VALIDATERISKPOLICY Validate the approved generic risk policy version 1.

required = ["policyVersion";"maximumUncertainty";"minimumConfidence"; ...
    "mediumHealthThreshold";"lowHealthThreshold"];
valid = isstruct(policy) && isscalar(policy) && ...
    isequal(string(fieldnames(policy)),required) && ...
    scalarOfClass(policy.policyVersion,"uint16") && policy.policyVersion == 1 && ...
    scalarOfClass(policy.maximumUncertainty,"single") && ...
    policy.maximumUncertainty == single(0.20) && ...
    scalarOfClass(policy.minimumConfidence,"single") && ...
    policy.minimumConfidence == single(0.80) && ...
    scalarOfClass(policy.mediumHealthThreshold,"single") && ...
    policy.mediumHealthThreshold == single(50) && ...
    scalarOfClass(policy.lowHealthThreshold,"single") && ...
    policy.lowHealthThreshold == single(80);
end

function valid = scalarOfClass(value,className)
valid = isa(value,className) && isscalar(value) && isreal(value) && isfinite(value);
end
