classdef PipelineFeatureAdapter
    %PIPELINEFEATUREADAPTER Project mapping and ridge-predictor execution.
    % The approved upstream feature contract enforces location availability
    % only when a detection is present; this adapter does not relax it.

    methods (Static)
        function featureSet = adapt(detectionFeatures, projectValues, projectValidity, configuration)
            featureSet = PipelineFeatureAdapter.emptyFeatureSet();
            if ~PipelineFeatureAdapter.validInputs(detectionFeatures, projectValues, ...
                    projectValidity, configuration)
                return
            end

            featureSet.featureSetId = configuration.featureSetId;
            featureSet.sourceRefs(1:2) = uint32([detectionFeatures.featureSetId; configuration.projectSourceRef]);
            featureSet.unitDeclarations(1:15) = uint16([1;1;1;2;2;3;3;3;4;5;6;7;8;9;7]);
            featureSet.extractorVersion = uint16(1);
            featureSet.schemaVersion = uint16(1);
            featureSet.featureIds(1:15) = uint16((101:115).');
            featureSet.featureCount = uint8(15);
            featureSet.referenceCount = uint8(2);

            featureSet.featureValues(1:5) = detectionFeatures.featureValues(1:5);
            featureSet.validity(1:5) = detectionFeatures.validity(1:5);
            featureSet.featureValues(6:15) = projectValues;
            featureSet.validity(6:15) = projectValidity;

            ranges = single([-80 300; -80 80; -160 380; 0 1e6; 0 1e5; ...
                -5e4 5e4; 0 3650; 0 65535; 0 100; 0 3650]);
            for k = 1:10
                if ~projectValidity(k) || ~isfinite(projectValues(k)) || ...
                        projectValues(k) < ranges(k,1) || projectValues(k) > ranges(k,2)
                    featureSet.featureValues(k+5) = single(0);
                    featureSet.validity(k+5) = false;
                end
            end
        end

        function raw = execute(featureSet, modelData)
            raw = struct("estimate",single(0),"uncertainty",single(0), ...
                "outOfDistribution",true);
            if ~PipelineFeatureAdapter.validModel(modelData) || ...
                    ~PipelineFeatureAdapter.validProjectFeatureSet(featureSet)
                return
            end
            activeIds = uint16([101;102;103;(106:115).']);
            [present, positions] = ismember(activeIds, featureSet.featureIds(1:double(featureSet.featureCount)));
            if ~all(present) || ~all(featureSet.validity(positions))
                raw.uncertainty = single(modelData.uncertainty);
                return
            end
            values = double(featureSet.featureValues(positions)).';
            if any(~isfinite(values))
                raw.uncertainty = single(modelData.uncertainty);
                return
            end
            standardized = (values - modelData.trainingMeans) ./ modelData.trainingStandardDeviations;
            estimate = [1 standardized] * modelData.coefficients;
            raw.estimate = single(min(max(estimate,0),100));
            raw.uncertainty = single(modelData.uncertainty);
            raw.outOfDistribution = false;
        end
    end

    methods (Static, Access=private)
        function valid = validInputs(detectionFeatures, values, validity, configuration)
            required = ["featureSetId";"projectSourceRef"];
            valid = iiw.features.validateFeatureSet(detectionFeatures) && ...
                detectionFeatures.featureCount == uint8(6) && ...
                isa(values,"single") && isequal(size(values),[10 1]) && ...
                isa(validity,"logical") && isequal(size(validity),[10 1]) && ...
                isstruct(configuration) && isscalar(configuration) && ...
                isequal(string(fieldnames(configuration)),required) && ...
                isa(configuration.featureSetId,"uint32") && isscalar(configuration.featureSetId) && ...
                configuration.featureSetId ~= 0 && ...
                isa(configuration.projectSourceRef,"uint32") && ...
                isscalar(configuration.projectSourceRef) && configuration.projectSourceRef ~= 0;
        end

        function valid = validProjectFeatureSet(value)
            required = ["featureSetId";"sourceRefs";"unitDeclarations";"validity"; ...
                "extractorVersion";"schemaVersion";"featureIds";"featureValues"; ...
                "featureCount";"referenceCount"];
            valid = isstruct(value) && isscalar(value) && ...
                isequal(string(fieldnames(value)),required) && ...
                isa(value.featureSetId,"uint32") && isscalar(value.featureSetId) && value.featureSetId~=0 && ...
                isa(value.sourceRefs,"uint32") && isequal(size(value.sourceRefs),[16 1]) && ...
                isa(value.unitDeclarations,"uint16") && isequal(size(value.unitDeclarations),[32 1]) && ...
                isa(value.validity,"logical") && isequal(size(value.validity),[32 1]) && ...
                isa(value.featureIds,"uint16") && isequal(size(value.featureIds),[32 1]) && ...
                isa(value.featureValues,"single") && isequal(size(value.featureValues),[32 1]) && ...
                value.featureCount==uint8(15) && value.referenceCount==uint8(2) && ...
                value.extractorVersion==uint16(1) && value.schemaVersion==uint16(1) && ...
                isequal(value.featureIds(1:15),uint16((101:115).')) && ...
                all(value.featureIds(16:end)==0) && all(value.sourceRefs(1:2)~=0) && ...
                all(value.sourceRefs(3:end)==0) && all(isfinite(value.featureValues(value.validity))) && ...
                all(value.featureValues(~value.validity)==0);
        end

        function valid = validModel(value)
            fields = ["modelId";"modelVersion";"featureSchemaVersion"; ...
                "extractorVersion";"activeFeatureIds";"lambda";"trainingMeans"; ...
                "trainingStandardDeviations";"coefficients";"validationRMSE"; ...
                "uncertainty";"contextId";"generatorVersion";"seed"];
            valid = isstruct(value) && isscalar(value) && ...
                isequal(string(fieldnames(value)),fields) && ...
                isequal(value.activeFeatureIds,uint16([101;102;103;(106:115).'])) && ...
                isequal(size(value.trainingMeans),[1 13]) && ...
                isequal(size(value.trainingStandardDeviations),[1 13]) && ...
                all(isfinite(value.trainingMeans)) && ...
                all(isfinite(value.trainingStandardDeviations)) && ...
                all(value.trainingStandardDeviations>0) && ...
                isequal(size(value.coefficients),[14 1]) && all(isfinite(value.coefficients)) && ...
                value.lambda==0.1 && isfinite(value.validationRMSE) && ...
                value.validationRMSE>=0 && value.uncertainty>=0 && value.uncertainty<=1;
        end

        function value = emptyFeatureSet()
            value = struct("featureSetId",uint32(0),"sourceRefs",zeros(16,1,"uint32"), ...
                "unitDeclarations",zeros(32,1,"uint16"),"validity",false(32,1), ...
                "extractorVersion",uint16(0),"schemaVersion",uint16(0), ...
                "featureIds",zeros(32,1,"uint16"),"featureValues",zeros(32,1,"single"), ...
                "featureCount",uint8(0),"referenceCount",uint8(0));
        end
    end
end
