function [action,boundary] = recommendation_adapter(quality,detection,risk,approval,configuration)
%RECOMMENDATION_ADAPTER Map accepted generic evidence to an advisory request.

[action,boundary] = emptyOutputs();
try
    if ~validConfiguration(configuration) || ~validQuality(quality)
        return
    end
    action.configurationVersion = configuration.configurationVersion;
    action.recommendationId = configuration.recommendationId;
    action.validFrom = configuration.validFrom;
    action.validUntil = configuration.validUntil;

    if quality.status ~= uint8(1)
        action.actionCode = uint8(4);
        boundary.statusCode = uint8(2);
        boundary.humanApprovalRequired = true;
        return
    end
    if ~validDetection(detection,configuration)
        action.actionCode = uint8(1);
        boundary.statusCode = uint8(3);
        boundary.humanApprovalRequired = true;
        return
    end
    if ~validRisk(risk)
        action.actionCode = uint8(1);
        boundary.statusCode = uint8(4);
        boundary.humanApprovalRequired = true;
        return
    end

    action.evidenceRefs = risk.evidenceRefs;
    action.referenceCount = risk.referenceCount;
    action.confidenceStatus = risk.confidenceStatus;
    action.actionCode = mapRisk(risk.riskLevel);
    action.approvalStatus = approvalStateOrMissing(approval);
    boundary.humanApprovalRequired = action.actionCode ~= uint8(0);
    boundary.statusCode = uint8(1);
    boundary.controlled = true;
    boundary.forwardingEligible = boundary.humanApprovalRequired && ...
        validCurrentApproval(approval,action.recommendationId) && ...
        action.actionCode >= uint8(1) && action.actionCode <= uint8(4);
catch
    [action,boundary] = emptyOutputs();
end
end

function code = mapRisk(level)
switch level
    case uint8(1), code = uint8(0);
    case uint8(2), code = uint8(2);
    case uint8(3), code = uint8(3);
    otherwise, code = uint8(1);
end
end

function valid = validConfiguration(value)
required = ["configurationVersion";"recommendationId";"validFrom"; ...
    "validUntil";"detectionSchemaVersion";"minimumConfidence"];
valid = isstruct(value) && isscalar(value) && all(isfield(value,required)) && ...
    scalar(value.configurationVersion,"uint16",true) && ...
    scalar(value.recommendationId,"uint32",true) && ...
    scalar(value.validFrom,"uint64",true) && scalar(value.validUntil,"uint64",true) && ...
    value.validUntil > value.validFrom && ...
    scalar(value.detectionSchemaVersion,"uint16",true) && ...
    isa(value.minimumConfidence,"single") && isscalar(value.minimumConfidence) && ...
    isfinite(value.minimumConfidence) && value.minimumConfidence >= 0 && value.minimumConfidence <= 1;
end

function valid = validQuality(value)
required = ["itemId";"status";"validatorVersion"];
valid = isstruct(value) && isscalar(value) && all(isfield(value,required)) && ...
    scalar(value.itemId,"uint32",true) && scalar(value.status,"uint8",true) && ...
    any(value.status == uint8([1 2 3])) && scalar(value.validatorVersion,"uint16",true);
end

function valid = validDetection(value,configuration)
required = ["resultId";"processedItemId";"labelId";"confidence"; ...
    "schemaVersion";"confidenceValid"];
valid = isstruct(value) && isscalar(value) && all(isfield(value,required)) && ...
    scalar(value.resultId,"uint32",true) && scalar(value.processedItemId,"uint32",true) && ...
    scalar(value.labelId,"uint8",false) && any(value.labelId == uint8([0 1])) && ...
    isa(value.confidence,"single") && isscalar(value.confidence) && ...
    isfinite(value.confidence) && value.confidence >= 0 && value.confidence <= 1 && ...
    islogical(value.confidenceValid) && isscalar(value.confidenceValid) && ...
    value.confidenceValid && value.confidence >= configuration.minimumConfidence && ...
    scalar(value.schemaVersion,"uint16",true) && ...
    value.schemaVersion == configuration.detectionSchemaVersion;
end

function valid = validRisk(value)
required = ["assessmentId";"evidenceRefs";"referenceCount"; ...
    "riskLevel";"confidenceStatus";"policyVersion"];
valid = isstruct(value) && isscalar(value) && all(isfield(value,required)) && ...
    scalar(value.assessmentId,"uint32",true) && ...
    isa(value.evidenceRefs,"uint32") && isequal(size(value.evidenceRefs),[16 1]) && ...
    scalar(value.referenceCount,"uint8",false) && value.referenceCount <= 16 && ...
    all(value.evidenceRefs(1:double(value.referenceCount)) ~= 0) && ...
    all(value.evidenceRefs(double(value.referenceCount)+1:end) == 0) && ...
    scalar(value.riskLevel,"uint8",true) && any(value.riskLevel == uint8(1:4)) && ...
    scalar(value.confidenceStatus,"uint8",true) && ...
    scalar(value.policyVersion,"uint16",true);
end

function state = approvalStateOrMissing(value)
state = uint8(0);
if isstruct(value) && isscalar(value) && isfield(value,"approvalState") && ...
        scalar(value.approvalState,"uint8",false) && value.approvalState <= 5
    state = value.approvalState;
end
end

function valid = validCurrentApproval(value,recommendationId)
required = ["recommendationId";"approvalState";"forwardingEligible"; ...
    "safetyBypass";"auditValid"];
valid = isstruct(value) && isscalar(value) && all(isfield(value,required)) && ...
    scalar(value.recommendationId,"uint32",true) && value.recommendationId == recommendationId && ...
    scalar(value.approvalState,"uint8",true) && value.approvalState == uint8(5) && ...
    islogical(value.forwardingEligible) && isscalar(value.forwardingEligible) && value.forwardingEligible && ...
    islogical(value.safetyBypass) && isscalar(value.safetyBypass) && ~value.safetyBypass && ...
    islogical(value.auditValid) && isscalar(value.auditValid) && value.auditValid;
end

function valid = scalar(value,className,nonzero)
valid = isa(value,className) && isscalar(value) && isreal(value) && isfinite(double(value));
if valid && nonzero, valid = value ~= 0; end
end

function [action,boundary] = emptyOutputs()
action = struct("recommendationId",uint32(0),"actionCode",uint8(255), ...
    "parameters",zeros(16,1,"single"),"evidenceRefs",zeros(16,1,"uint32"), ...
    "confidenceStatus",uint8(0),"approvalStatus",uint8(0), ...
    "validFrom",uint64(0),"validUntil",uint64(0), ...
    "configurationVersion",uint16(0),"parameterCount",uint8(0), ...
    "referenceCount",uint8(0));
boundary = struct("forwardingEligible",false,"humanApprovalRequired",true, ...
    "advisoryOnly",true,"controlled",false,"statusCode",uint8(255));
end

