function [inspectionData,inspectionMetadata,status] = source_adapter(frame,context,configuration)
%SOURCE_ADAPTER Map a simulated camera frame/context to generic contracts.

[inspectionData,inspectionMetadata,status] = emptyOutputs();
try
    if ~validConfiguration(configuration) || ~validContext(context,configuration) || ...
            ~validFrame(frame,context)
        return
    end

    inspectionData.itemId = context.itemId;
    inspectionData.payloadRef = context.payloadRef;
    inspectionData.modality = uint8(1);
    inspectionData.sourceId = configuration.sourceId;
    inspectionData.sequenceId = context.sequenceId;
    inspectionData.timestamp = context.captureTimestamp;
    inspectionData.schemaVersion = configuration.inspectionDataSchemaVersion;

    inspectionMetadata.itemId = context.itemId;
    inspectionMetadata.acquisitionContext = context.acquisitionContextRef;
    inspectionMetadata.calibrationRef = context.cameraCalibrationRef;
    inspectionMetadata.contextSchemaVersion = context.metadataVersion;

    status.accepted = true;
    status.statusCode = uint8(1);
    status.itemId = context.itemId;
    status.contextValid = true;
    status.frameValid = true;
catch
    [inspectionData,inspectionMetadata,status] = emptyOutputs();
end
end

function valid = validConfiguration(value)
required = ["sourceId";"inspectionDataSchemaVersion";"metadataSchemaVersion"];
valid = isstruct(value) && isscalar(value) && all(isfield(value,required)) && ...
    scalarOfClass(value.sourceId,"uint32",true) && ...
    scalarOfClass(value.inspectionDataSchemaVersion,"uint16",true) && ...
    scalarOfClass(value.metadataSchemaVersion,"uint16",true);
end

function valid = validContext(value,configuration)
required = ["itemId";"payloadRef";"acquisitionContextRef";"assetId"; ...
    "pipelineSectionId";"inspectionPlanId";"simulationRunId"; ...
    "sceneConfigurationId";"cameraId";"cameraCalibrationRef"; ...
    "sequenceId";"coordinateFrameId";"captureTimestamp";"imageWidth"; ...
    "imageHeight";"channelCount";"platformPosition"; ...
    "platformOrientation";"metadataVersion";"configurationVersion"];
if ~(isstruct(value) && isscalar(value) && all(isfield(value,required)))
    valid = false;
    return
end
uint32Fields = ["itemId";"payloadRef";"acquisitionContextRef";"assetId"; ...
    "pipelineSectionId";"inspectionPlanId";"simulationRunId"; ...
    "sceneConfigurationId";"cameraId";"cameraCalibrationRef";"sequenceId"];
valid = all(arrayfun(@(name) scalarOfClass(value.(name),"uint32",true),uint32Fields)) && ...
    scalarOfClass(value.coordinateFrameId,"uint16",true) && ...
    scalarOfClass(value.captureTimestamp,"uint64",true) && ...
    scalarOfClass(value.imageWidth,"uint16",true) && ...
    scalarOfClass(value.imageHeight,"uint16",true) && ...
    scalarOfClass(value.channelCount,"uint8",true) && ...
    any(value.channelCount == uint8([1 3])) && ...
    isa(value.platformPosition,"double") && isequal(size(value.platformPosition),[3 1]) && ...
    all(isfinite(value.platformPosition)) && ...
    isa(value.platformOrientation,"double") && isequal(size(value.platformOrientation),[4 1]) && ...
    all(isfinite(value.platformOrientation)) && ...
    abs(norm(value.platformOrientation)-1) <= 1e-12 && ...
    scalarOfClass(value.metadataVersion,"uint16",true) && ...
    value.metadataVersion == configuration.metadataSchemaVersion && ...
    scalarOfClass(value.configurationVersion,"uint16",true);
end

function valid = validFrame(frame,context)
valid = (isa(frame,"uint8") || isa(frame,"uint16") || ...
    isa(frame,"single") || isa(frame,"double")) && ~isempty(frame) && ...
    all(isfinite(frame(:))) && ndims(frame) <= 3 && ...
    size(frame,1) == double(context.imageHeight) && ...
    size(frame,2) == double(context.imageWidth);
if valid
    actualChannels = 1;
    if ndims(frame) == 3, actualChannels = size(frame,3); end
    valid = actualChannels == double(context.channelCount);
end
end

function valid = scalarOfClass(value,className,nonzero)
valid = isa(value,className) && isscalar(value) && isreal(value) && isfinite(double(value));
if valid && nonzero, valid = value ~= 0; end
end

function [data,metadata,status] = emptyOutputs()
data = struct("itemId",uint32(0),"payloadRef",uint32(0), ...
    "modality",uint8(0),"sourceId",uint32(0),"sequenceId",uint32(0), ...
    "timestamp",uint64(0),"schemaVersion",uint16(0));
metadata = struct("itemId",uint32(0),"acquisitionContext",uint32(0), ...
    "calibrationRef",uint32(0),"contextSchemaVersion",uint16(0));
status = struct("accepted",false,"statusCode",uint8(2),"itemId",uint32(0), ...
    "contextValid",false,"frameValid",false);
end
