function featureSet = extractNumericalFeatures(detectionResult, configuration)
%EXTRACTNUMERICALFEATURES Convert DetectionResult to catalog-v1 features.

featureSet = emptyFeatureSet();
if ~validConfiguration(configuration) || ~validDetectionResult(detectionResult)
    return
end

featureSet.featureSetId = configuration.featureSetId;
featureSet.sourceRefs(1) = detectionResult.resultId;
featureSet.unitDeclarations(1:6) = uint16([1; 1; 1; 2; 2; 2]);
featureSet.extractorVersion = uint16(1);
featureSet.schemaVersion = uint16(1);
featureSet.featureIds(1:6) = uint16((1:6).');
featureSet.featureCount = uint8(6);
featureSet.referenceCount = uint8(1);

detectionPresent = detectionResult.labelId >= uint8(1) && ...
    detectionResult.labelId <= uint8(254);
featureSet.featureValues(1) = single(detectionPresent);
featureSet.validity(1) = true;

if detectionResult.confidenceValid
    featureSet.featureValues(2) = detectionResult.confidence;
    featureSet.validity(2) = true;
end

if ~detectionPresent
    featureSet.featureValues(3) = single(0);
    featureSet.validity(3) = true;
    return
end

featureSet.featureValues(3) = single(detectionResult.locationValid);
featureSet.validity(3) = true;
if detectionResult.locationValid
    coordinates = single(detectionResult.location);
    if ~all(isfinite(coordinates))
        featureSet = emptyFeatureSet();
        return
    end
    featureSet.featureValues(4:6) = coordinates;
    featureSet.validity(4:6) = true;
end
end

function valid = validConfiguration(value)
required = ["featureSetId"; "detectionSchemaVersion"; ...
    "featureSchemaVersion"; "catalogVersion"; "extractorVersion"];
valid = isstruct(value) && isscalar(value) && ...
    isequal(string(fieldnames(value)), required) && ...
    scalarOfClass(value.featureSetId, "uint32") && value.featureSetId ~= 0 && ...
    scalarOfClass(value.detectionSchemaVersion, "uint16") && ...
    value.detectionSchemaVersion == uint16(1) && ...
    scalarOfClass(value.featureSchemaVersion, "uint16") && ...
    value.featureSchemaVersion == uint16(1) && ...
    scalarOfClass(value.catalogVersion, "uint16") && ...
    value.catalogVersion == uint16(1) && ...
    scalarOfClass(value.extractorVersion, "uint16") && ...
    value.extractorVersion == uint16(1);
end

function valid = validDetectionResult(value)
required = ["resultId"; "processedItemId"; "labelId"; "confidence"; ...
    "location"; "modelVersion"; "schemaVersion"; "confidenceValid"; ...
    "locationValid"; "frameId"];
valid = isstruct(value) && isscalar(value) && ...
    isequal(string(fieldnames(value)), required) && ...
    scalarOfClass(value.resultId, "uint32") && value.resultId ~= 0 && ...
    scalarOfClass(value.processedItemId, "uint32") && ...
    value.processedItemId ~= 0 && ...
    scalarOfClass(value.labelId, "uint8") && value.labelId ~= uint8(255) && ...
    scalarOfClass(value.confidence, "single") && isfinite(value.confidence) && ...
    value.confidence >= single(0) && value.confidence <= single(1) && ...
    isa(value.location, "double") && isequal(size(value.location), [3 1]) && ...
    all(isfinite(value.location)) && ...
    scalarOfClass(value.modelVersion, "uint16") && ...
    scalarOfClass(value.schemaVersion, "uint16") && ...
    value.schemaVersion == uint16(1) && ...
    scalarOfClass(value.confidenceValid, "logical") && ...
    scalarOfClass(value.locationValid, "logical") && ...
    scalarOfClass(value.frameId, "uint16") && ...
    (value.confidenceValid || value.confidence == single(0)) && ...
    (value.locationValid || all(value.location == 0)) && ...
    ((value.locationValid && value.frameId ~= 0) || ...
    (~value.locationValid && value.frameId == 0));
end

function valid = scalarOfClass(value, className)
valid = isa(value, className) && isscalar(value) && isreal(value);
end

function value = emptyFeatureSet()
value = struct( ...
    "featureSetId", uint32(0), ...
    "sourceRefs", zeros(16, 1, "uint32"), ...
    "unitDeclarations", zeros(32, 1, "uint16"), ...
    "validity", false(32, 1), ...
    "extractorVersion", uint16(0), ...
    "schemaVersion", uint16(0), ...
    "featureIds", zeros(32, 1, "uint16"), ...
    "featureValues", zeros(32, 1, "single"), ...
    "featureCount", uint8(0), ...
    "referenceCount", uint8(0));
end
