function valid = validateFeatureSet(value)
%VALIDATEFEATURESET Validate approved empty or catalog-v1 feature sets.

valid = hasSchema(value);
if ~valid
    return
end

if value.featureCount == 0
    valid = value.referenceCount == 0 && value.featureSetId == 0 && ...
        value.extractorVersion == 0 && value.schemaVersion == 0 && ...
        all(value.sourceRefs == 0) && all(value.unitDeclarations == 0) && ...
        ~any(value.validity) && all(value.featureIds == 0) && ...
        all(value.featureValues == 0);
    return
end

valid = value.featureCount == uint8(6) && value.referenceCount == uint8(1) && ...
    value.featureSetId ~= 0 && value.sourceRefs(1) ~= 0 && ...
    all(value.sourceRefs(2:end) == 0) && ...
    value.extractorVersion == uint16(1) && value.schemaVersion == uint16(1) && ...
    isequal(value.featureIds(1:6), uint16((1:6).')) && ...
    all(value.featureIds(7:end) == 0) && ...
    isequal(value.unitDeclarations(1:6), uint16([1; 1; 1; 2; 2; 2])) && ...
    all(value.unitDeclarations(7:end) == 0) && ...
    all(isfinite(value.featureValues)) && ...
    value.validity(1) && value.validity(3) && ...
    any(value.featureValues(1) == single([0 1])) && ...
    any(value.featureValues(3) == single([0 1])) && ...
    (~value.validity(2) || (value.featureValues(2) >= 0 && ...
    value.featureValues(2) <= 1)) && ...
    (value.validity(2) || value.featureValues(2) == 0) && ...
    all(value.validity(4:6) == logical(value.featureValues(3))) && ...
    (~logical(value.featureValues(3)) || logical(value.featureValues(1))) && ...
    (~logical(value.featureValues(3)) || all(isfinite(value.featureValues(4:6)))) && ...
    (logical(value.featureValues(3)) || all(value.featureValues(4:6) == 0)) && ...
    ~any(value.validity(7:end)) && all(value.featureValues(7:end) == 0);
end

function valid = hasSchema(value)
required = ["featureSetId"; "sourceRefs"; "unitDeclarations"; "validity"; ...
    "extractorVersion"; "schemaVersion"; "featureIds"; "featureValues"; ...
    "featureCount"; "referenceCount"];
valid = isstruct(value) && isscalar(value) && ...
    isequal(string(fieldnames(value)), required) && ...
    scalar(value.featureSetId, "uint32") && ...
    vector(value.sourceRefs, "uint32", 16) && ...
    vector(value.unitDeclarations, "uint16", 32) && ...
    vector(value.validity, "logical", 32) && ...
    scalar(value.extractorVersion, "uint16") && ...
    scalar(value.schemaVersion, "uint16") && ...
    vector(value.featureIds, "uint16", 32) && ...
    vector(value.featureValues, "single", 32) && ...
    scalar(value.featureCount, "uint8") && value.featureCount <= 32 && ...
    scalar(value.referenceCount, "uint8") && value.referenceCount <= 16;
end

function valid = scalar(value, className)
valid = isa(value, className) && isscalar(value) && isreal(value);
end

function valid = vector(value, className, lengthValue)
valid = isa(value, className) && isequal(size(value), [lengthValue 1]) && ...
    isreal(value);
end
