classdef DetectorContract
    %DETECTORCONTRACT Contract helpers for replaceable detection functions.

    methods (Static)
        function detector = create(executeFcn, implementationId, implementationVersion)
            arguments
                executeFcn (1,1) function_handle
                implementationId (1,1) uint32 {mustBeNonzero}
                implementationVersion (1,1) uint16 {mustBeNonzero}
            end

            detector = struct( ...
                "execute", executeFcn, ...
                "implementationId", implementationId, ...
                "implementationVersion", implementationVersion);
        end

        function valid = isConformingDetector(detector)
            required = ["execute"; "implementationId"; "implementationVersion"];
            valid = isstruct(detector) && isscalar(detector) && ...
                isequal(string(fieldnames(detector)), required) && ...
                isa(detector.execute, "function_handle") && ...
                isa(detector.implementationId, "uint32") && ...
                isscalar(detector.implementationId) && detector.implementationId ~= 0 && ...
                isa(detector.implementationVersion, "uint16") && ...
                isscalar(detector.implementationVersion) && ...
                detector.implementationVersion ~= 0;
        end

        function valid = isValidProcessedData(value)
            required = ["processedItemId"; "sourceItemId"; "representationRef"; ...
                "transformRecordRef"; "configurationVersion"; "schemaVersion"];
            valid = isstruct(value) && isscalar(value) && ...
                isequal(string(fieldnames(value)), required) && ...
                validNonzeroScalar(value.processedItemId, "uint32") && ...
                validNonzeroScalar(value.sourceItemId, "uint32") && ...
                validNonzeroScalar(value.representationRef, "uint32") && ...
                validNonzeroScalar(value.transformRecordRef, "uint32") && ...
                validNonzeroScalar(value.configurationVersion, "uint16") && ...
                validNonzeroScalar(value.schemaVersion, "uint16");
        end

        function valid = hasDetectionResultSchema(value)
            required = ["resultId"; "processedItemId"; "labelId"; "confidence"; ...
                "location"; "modelVersion"; "schemaVersion"; ...
                "confidenceValid"; "locationValid"; "frameId"];
            valid = isstruct(value) && isscalar(value) && ...
                isequal(string(fieldnames(value)), required) && ...
                validScalar(value.resultId, "uint32") && ...
                validScalar(value.processedItemId, "uint32") && ...
                validScalar(value.labelId, "uint8") && ...
                validScalar(value.confidence, "single") && ...
                isfinite(value.confidence) && value.confidence >= 0 && ...
                value.confidence <= 1 && ...
                isa(value.location, "double") && isequal(size(value.location), [3 1]) && ...
                all(isfinite(value.location)) && ...
                validScalar(value.modelVersion, "uint16") && ...
                validScalar(value.schemaVersion, "uint16") && ...
                validScalar(value.confidenceValid, "logical") && ...
                validScalar(value.locationValid, "logical") && ...
                validScalar(value.frameId, "uint16") && ...
                (value.confidenceValid || value.confidence == 0) && ...
                (value.locationValid || all(value.location == 0)) && ...
                ((value.locationValid && value.frameId ~= 0) || ...
                (~value.locationValid && value.frameId == 0));
        end

        function valid = isValidDetectionResult(value)
            valid = iiw.detection.DetectorContract.hasDetectionResultSchema(value) && ...
                value.resultId ~= 0 && value.processedItemId ~= 0 && ...
                value.labelId ~= uint8(255) && value.confidenceValid && ...
                value.modelVersion ~= 0 && value.schemaVersion ~= 0;
        end

        function result = invalidResult()
            result = struct( ...
                "resultId", uint32(0), ...
                "processedItemId", uint32(0), ...
                "labelId", uint8(255), ...
                "confidence", single(0), ...
                "location", zeros(3, 1, "double"), ...
                "modelVersion", uint16(0), ...
                "schemaVersion", uint16(0), ...
                "confidenceValid", false, ...
                "locationValid", false, ...
                "frameId", uint16(0));
        end
    end
end

function valid = validNonzeroScalar(value, className)
valid = validScalar(value, className) && value ~= 0;
end

function valid = validScalar(value, className)
valid = isa(value, className) && isscalar(value) && isreal(value);
end
