function [result, executionStatus] = runDetector(processedData, imageData, detector, configuration)
%RUNDETECTOR Execute a configured detector through the common contract.
%   executionStatus encodings are 0=DETECTED, 1=NO_DETECTION,
%   2=LOW_CONFIDENCE, 3=MALFORMED_INPUT, 4=EXECUTION_FAILURE,
%   and 5=INVALID_RESULT.

result = iiw.detection.DetectorContract.invalidResult();
executionStatus = uint8(3);

if ~iiw.detection.DetectorContract.isValidProcessedData(processedData) || ...
        ~iiw.detection.DetectorContract.isConformingDetector(detector) || ...
        ~validImageData(imageData) || ~validRunConfiguration(configuration)
    return
end

try
    candidate = detector.execute(processedData, imageData, configuration, detector);
catch
    executionStatus = uint8(4);
    return
end

if ~iiw.detection.DetectorContract.isValidDetectionResult(candidate) || ...
        candidate.processedItemId ~= processedData.processedItemId || ...
        candidate.modelVersion ~= detector.implementationVersion || ...
        candidate.schemaVersion ~= configuration.resultSchemaVersion
    executionStatus = uint8(5);
    return
end

result = candidate;
if result.labelId == uint8(0)
    executionStatus = uint8(1);
elseif result.confidence < configuration.minimumConfidence
    result.labelId = uint8(0);
    result.location = zeros(3, 1, "double");
    result.locationValid = false;
    result.frameId = uint16(0);
    executionStatus = uint8(2);
else
    executionStatus = uint8(0);
end
end

function valid = validImageData(value)
valid = (isnumeric(value) || islogical(value)) && isreal(value) && ...
    ~isempty(value) && (ismatrix(value) || (ndims(value) == 3 && size(value, 3) == 3)) && ...
    all(isfinite(value(:)));
end

function valid = validRunConfiguration(value)
required = ["resultId"; "labelId"; "resultSchemaVersion"; ...
    "minimumConfidence"; "detectionMode"; "intensityThreshold"; ...
    "minimumArea"; "smoothingSigma"; "emitLocation"; ...
    "locationScale"; "locationOrigin"; "frameId"];
valid = isstruct(value) && isscalar(value) && ...
    isequal(string(fieldnames(value)), required) && ...
    validNonzero(value.resultId, "uint32") && ...
    isa(value.labelId, "uint8") && isscalar(value.labelId) && ...
    value.labelId > 0 && value.labelId < 255 && ...
    validNonzero(value.resultSchemaVersion, "uint16") && ...
    unitSingle(value.minimumConfidence) && ...
    isa(value.detectionMode, "uint8") && isscalar(value.detectionMode) && ...
    any(value.detectionMode == uint8([1 2])) && ...
    unitSingle(value.intensityThreshold) && ...
    validNonzero(value.minimumArea, "uint32") && ...
    isa(value.smoothingSigma, "single") && isscalar(value.smoothingSigma) && ...
    isfinite(value.smoothingSigma) && value.smoothingSigma >= 0 && ...
    isa(value.emitLocation, "logical") && isscalar(value.emitLocation) && ...
    isa(value.locationScale, "double") && isequal(size(value.locationScale), [2 1]) && ...
    all(isfinite(value.locationScale)) && all(value.locationScale > 0) && ...
    isa(value.locationOrigin, "double") && isequal(size(value.locationOrigin), [3 1]) && ...
    all(isfinite(value.locationOrigin)) && ...
    isa(value.frameId, "uint16") && isscalar(value.frameId) && ...
    ((value.emitLocation && value.frameId ~= 0) || ~value.emitLocation);
end

function valid = unitSingle(value)
valid = isa(value, "single") && isscalar(value) && isfinite(value) && ...
    value >= 0 && value <= 1;
end

function valid = validNonzero(value, className)
valid = isa(value, className) && isscalar(value) && isreal(value) && value ~= 0;
end
