function prediction = predictHealth(featureSet, predictor, configuration)
%PREDICTHEALTH Execute a replaceable predictor through generic contracts.

prediction = invalidPrediction();

if ~validConfiguration(configuration) || ...
        ~isa(predictor, "iiw.prediction.PredictorContract") || ...
        ~validPredictorIdentity(predictor, configuration) || ...
        ~validFeatureSet(featureSet, predictor)
    return
end

try
    raw = predictor.execute(featureSet);
catch
    return
end

if ~validRawOutput(raw)
    return
end

if raw.outOfDistribution
    prediction = reviewPrediction(featureSet, predictor, configuration, raw);
    return
end

prediction.predictionId = configuration.predictionId;
prediction.featureSetId = featureSet.featureSetId;
prediction.estimate = min(max(single(raw.estimate), single(0)), single(100));
prediction.contextOrHorizon = configuration.contextOrHorizon;
prediction.uncertainty = single(raw.uncertainty);
prediction.confidenceStatus = uint8(1);
if prediction.uncertainty > configuration.maximumUncertainty
    prediction.confidenceStatus = uint8(2);
end
prediction.modelVersion = predictor.ModelVersion;
prediction.schemaVersion = configuration.schemaVersion;
prediction.estimateValid = true;
prediction.contextOrHorizonValid = true;
prediction.uncertaintyValid = true;

if ~iiw.prediction.validateHealthPrediction(prediction)
    prediction = invalidPrediction();
end
end

function valid = validConfiguration(value)
required = ["predictionId"; "contextOrHorizon"; "schemaVersion"; ...
    "maximumUncertainty"; "allowedModelVersions"];
valid = isstruct(value) && isscalar(value) && ...
    isequal(string(fieldnames(value)), required) && ...
    scalarOfClass(value.predictionId, "uint32") && value.predictionId ~= 0 && ...
    scalarOfClass(value.contextOrHorizon, "uint32") && ...
    value.contextOrHorizon ~= 0 && ...
    scalarOfClass(value.schemaVersion, "uint16") && ...
    value.schemaVersion == uint16(1) && ...
    scalarOfClass(value.maximumUncertainty, "single") && ...
    isfinite(value.maximumUncertainty) && ...
    value.maximumUncertainty >= 0 && value.maximumUncertainty <= 1 && ...
    isa(value.allowedModelVersions, "uint16") && ...
    iscolumn(value.allowedModelVersions) && ~isempty(value.allowedModelVersions);
end

function valid = validPredictorIdentity(value, configuration)
valid = scalarOfClass(value.ModelId, "uint32") && value.ModelId ~= 0 && ...
    scalarOfClass(value.ModelVersion, "uint16") && value.ModelVersion ~= 0 && ...
    isa(value.SupportedFeatureSchemaVersions, "uint16") && ...
    iscolumn(value.SupportedFeatureSchemaVersions) && ...
    isa(value.SupportedExtractorVersions, "uint16") && ...
    iscolumn(value.SupportedExtractorVersions) && ...
    isa(value.SupportedFeatureIds, "uint16") && ...
    iscolumn(value.SupportedFeatureIds) && ...
    ~isempty(value.SupportedFeatureSchemaVersions) && ...
    ~isempty(value.SupportedExtractorVersions) && ...
    ~isempty(value.SupportedFeatureIds) && ...
    isa(value.ExecuteFunction, "function_handle") && ...
    any(value.ModelVersion == configuration.allowedModelVersions);
end

function valid = validFeatureSet(value, predictor)
required = ["featureSetId"; "sourceRefs"; "unitDeclarations"; ...
    "validity"; "extractorVersion"; "schemaVersion"; "featureIds"; ...
    "featureValues"; "featureCount"; "referenceCount"];
valid = isstruct(value) && isscalar(value) && ...
    isequal(string(fieldnames(value)), required) && ...
    scalarOfClass(value.featureSetId, "uint32") && value.featureSetId ~= 0 && ...
    vectorOfClass(value.sourceRefs, "uint32", 16) && ...
    vectorOfClass(value.unitDeclarations, "uint16", 32) && ...
    vectorOfClass(value.validity, "logical", 32) && ...
    scalarOfClass(value.extractorVersion, "uint16") && ...
    scalarOfClass(value.schemaVersion, "uint16") && ...
    vectorOfClass(value.featureIds, "uint16", 32) && ...
    vectorOfClass(value.featureValues, "single", 32) && ...
    scalarOfClass(value.featureCount, "uint8") && value.featureCount > 0 && ...
    value.featureCount <= 32 && ...
    scalarOfClass(value.referenceCount, "uint8") && ...
    value.referenceCount > 0 && value.referenceCount <= 16;
if ~valid
    return
end

count = double(value.featureCount);
refCount = double(value.referenceCount);
activeIds = value.featureIds(1:count);
valid = any(value.schemaVersion == predictor.SupportedFeatureSchemaVersions) && ...
    any(value.extractorVersion == predictor.SupportedExtractorVersions) && ...
    isequal(activeIds, sort(activeIds)) && numel(unique(activeIds)) == count && ...
    all(ismember(activeIds, predictor.SupportedFeatureIds)) && ...
    all(activeIds ~= 0) && all(value.featureIds(count+1:end) == 0) && ...
    all(value.sourceRefs(1:refCount) ~= 0) && ...
    all(value.sourceRefs(refCount+1:end) == 0) && ...
    all(value.unitDeclarations(count+1:end) == 0) && ...
    ~any(value.validity(count+1:end)) && ...
    all(value.featureValues(count+1:end) == 0) && ...
    all(isfinite(value.featureValues(value.validity))) && ...
    all(value.featureValues(~value.validity) == 0);
end

function valid = validRawOutput(value)
required = ["estimate"; "uncertainty"; "outOfDistribution"];
valid = isstruct(value) && isscalar(value) && ...
    isequal(string(fieldnames(value)), required) && ...
    scalarOfClass(value.estimate, "single") && isfinite(value.estimate) && ...
    scalarOfClass(value.uncertainty, "single") && ...
    isfinite(value.uncertainty) && value.uncertainty >= 0 && ...
    value.uncertainty <= 1 && ...
    scalarOfClass(value.outOfDistribution, "logical");
end

function result = reviewPrediction(featureSet, predictor, configuration, raw)
result = invalidPrediction();
result.predictionId = configuration.predictionId;
result.featureSetId = featureSet.featureSetId;
result.contextOrHorizon = configuration.contextOrHorizon;
result.uncertainty = single(raw.uncertainty);
result.confidenceStatus = uint8(2);
result.modelVersion = predictor.ModelVersion;
result.schemaVersion = configuration.schemaVersion;
result.contextOrHorizonValid = true;
result.uncertaintyValid = true;
end

function result = invalidPrediction()
result = struct( ...
    "predictionId", uint32(0), ...
    "featureSetId", uint32(0), ...
    "estimate", single(0), ...
    "contextOrHorizon", uint32(0), ...
    "uncertainty", single(0), ...
    "confidenceStatus", uint8(4), ...
    "modelVersion", uint16(0), ...
    "schemaVersion", uint16(0), ...
    "estimateValid", false, ...
    "contextOrHorizonValid", false, ...
    "uncertaintyValid", false);
end

function valid = scalarOfClass(value, className)
valid = isa(value, className) && isscalar(value) && isreal(value);
end

function valid = vectorOfClass(value, className, lengthValue)
valid = isa(value, className) && isequal(size(value), [lengthValue 1]) && ...
    isreal(value);
end
