function valid = validateHealthPrediction(value)
%VALIDATEHEALTHPREDICTION Validate the approved eleven-field contract.

required = ["predictionId"; "featureSetId"; "estimate"; ...
    "contextOrHorizon"; "uncertainty"; "confidenceStatus"; ...
    "modelVersion"; "schemaVersion"; "estimateValid"; ...
    "contextOrHorizonValid"; "uncertaintyValid"];

valid = isstruct(value) && isscalar(value) && ...
    isequal(string(fieldnames(value)), required) && ...
    scalar(value.predictionId, "uint32") && ...
    scalar(value.featureSetId, "uint32") && ...
    scalar(value.estimate, "single") && isfinite(value.estimate) && ...
    scalar(value.contextOrHorizon, "uint32") && ...
    scalar(value.uncertainty, "single") && isfinite(value.uncertainty) && ...
    value.uncertainty >= 0 && value.uncertainty <= 1 && ...
    scalar(value.confidenceStatus, "uint8") && ...
    any(value.confidenceStatus == uint8(0:4)) && ...
    scalar(value.modelVersion, "uint16") && ...
    scalar(value.schemaVersion, "uint16") && ...
    scalar(value.estimateValid, "logical") && ...
    scalar(value.contextOrHorizonValid, "logical") && ...
    scalar(value.uncertaintyValid, "logical");
if ~valid
    return
end

if value.estimateValid
    valid = value.predictionId ~= 0 && value.featureSetId ~= 0 && ...
        value.estimate >= 0 && value.estimate <= 100 && ...
        value.contextOrHorizonValid && value.contextOrHorizon ~= 0 && ...
        value.uncertaintyValid && value.modelVersion ~= 0 && ...
        value.schemaVersion ~= 0 && ...
        any(value.confidenceStatus == uint8([1 2]));
elseif value.confidenceStatus == uint8(2)
    valid = value.predictionId ~= 0 && value.featureSetId ~= 0 && ...
        value.estimate == 0 && value.contextOrHorizonValid && ...
        value.contextOrHorizon ~= 0 && value.uncertaintyValid && ...
        value.modelVersion ~= 0 && value.schemaVersion ~= 0;
else
    valid = value.confidenceStatus == uint8(4) && ...
        value.predictionId == 0 && value.featureSetId == 0 && ...
        value.estimate == 0 && value.contextOrHorizon == 0 && ...
        value.uncertainty == 0 && value.modelVersion == 0 && ...
        value.schemaVersion == 0 && ~value.contextOrHorizonValid && ...
        ~value.uncertaintyValid;
end
end

function valid = scalar(value, className)
valid = isa(value, className) && isscalar(value) && isreal(value);
end
