function [inspectionData,inspectionMetadata,status] = source_adapter(frame,context,configuration)
%SOURCE_ADAPTER Map a stationary synthetic RGB source to generic contracts.

[inspectionData,inspectionMetadata,status] = emptyOutputs();
try
    if ~validConfiguration(configuration) || ~validContext(context,configuration) || ...
            ~validFrame(frame,context)
        return
    end
    inspectionData = struct("itemId",context.itemId,"payloadRef",context.payloadRef, ...
        "modality",uint8(1),"sourceId",configuration.sourceId, ...
        "sequenceId",context.sequenceId,"timestamp",context.captureTimestamp, ...
        "schemaVersion",configuration.inspectionDataSchemaVersion);
    inspectionMetadata = struct("itemId",context.itemId, ...
        "acquisitionContext",context.acquisitionContextRef, ...
        "calibrationRef",context.cameraCalibrationRef, ...
        "contextSchemaVersion",context.metadataVersion);
    status = struct("accepted",true,"statusCode",uint8(1), ...
        "itemId",context.itemId,"contextValid",true,"frameValid",true);
catch
    [inspectionData,inspectionMetadata,status] = emptyOutputs();
end
end

function valid = validConfiguration(value)
required = ["sourceId";"inspectionDataSchemaVersion";"metadataSchemaVersion"];
valid = isstruct(value) && isscalar(value) && all(isfield(value,required)) && ...
    scalarOfClass(value.sourceId,"uint32",true) && ...
    scalarOfClass(value.inspectionDataSchemaVersion,"uint16",true) && ...
    scalarOfClass(value.metadataSchemaVersion,"uint16",true);
end

function valid = validContext(value,configuration)
required = ["itemId";"payloadRef";"acquisitionContextRef";"stationId"; ...
    "partId";"cameraId";"cameraCalibrationRef";"sequenceId"; ...
    "captureTimestamp";"fixedReferenceFrameId";"imageWidth"; ...
    "imageHeight";"channelCount";"metadataVersion"; ...
    "configurationVersion";"stationary"];
if ~(isstruct(value) && isscalar(value) && all(isfield(value,required)))
    valid = false; return
end
ids = ["itemId";"payloadRef";"acquisitionContextRef";"stationId"; ...
    "partId";"cameraId";"cameraCalibrationRef";"sequenceId"];
valid = all(arrayfun(@(name) scalarOfClass(value.(name),"uint32",true),ids)) && ...
    scalarOfClass(value.captureTimestamp,"uint64",true) && ...
    scalarOfClass(value.fixedReferenceFrameId,"uint16",true) && ...
    scalarOfClass(value.imageWidth,"uint16",true) && ...
    scalarOfClass(value.imageHeight,"uint16",true) && ...
    scalarOfClass(value.channelCount,"uint8",true) && value.channelCount == uint8(3) && ...
    scalarOfClass(value.metadataVersion,"uint16",true) && ...
    value.metadataVersion == configuration.metadataSchemaVersion && ...
    scalarOfClass(value.configurationVersion,"uint16",true) && ...
    islogical(value.stationary) && isscalar(value.stationary) && value.stationary;
end

function valid = validFrame(frame,context)
valid = isa(frame,"uint8") && ~isempty(frame) && ndims(frame) == 3 && ...
    isequal(size(frame),[double(context.imageHeight),double(context.imageWidth),3]);
end

function valid = scalarOfClass(value,className,nonzero)
valid = isa(value,className) && isscalar(value) && isreal(value) && isfinite(double(value));
if valid && nonzero, valid = value ~= 0; end
end

function [data,metadata,status] = emptyOutputs()
data = struct("itemId",uint32(0),"payloadRef",uint32(0),"modality",uint8(0), ...
    "sourceId",uint32(0),"sequenceId",uint32(0),"timestamp",uint64(0), ...
    "schemaVersion",uint16(0));
metadata = struct("itemId",uint32(0),"acquisitionContext",uint32(0), ...
    "calibrationRef",uint32(0),"contextSchemaVersion",uint16(0));
status = struct("accepted",false,"statusCode",uint8(2),"itemId",uint32(0), ...
    "contextValid",false,"frameValid",false);
end

