function entry = recordTransform(order, operationCode, parameterIds, ...
    parameterValues, implementationVersion, configurationVersion, ...
    inputReference, outputReference)
%RECORDTRANSFORM Create one deterministic preprocessing transformation record.

entry = emptyEntry();

if nargin ~= 8 || ~validScalar(order, "uint8", false) || ...
        ~validScalar(operationCode, "uint8", false) || ...
        ~validScalar(implementationVersion, "uint16", false) || ...
        ~validScalar(configurationVersion, "uint16", false) || ...
        ~validScalar(inputReference, "uint32", false) || ...
        ~validScalar(outputReference, "uint32", false)
    error("iiw:preprocessing:InvalidTransformRecord", ...
        "Transformation metadata is incomplete or invalid.");
end

if ~isa(parameterIds, "uint16") || ~isa(parameterValues, "single") || ...
        ~isvector(parameterIds) || ~isvector(parameterValues)
    error("iiw:preprocessing:InvalidTransformParameters", ...
        "Parameter identifiers and values must use the approved numeric representations.");
end

parameterIds = parameterIds(:);
parameterValues = parameterValues(:);
parameterCount = numel(parameterIds);
if parameterCount ~= numel(parameterValues) || parameterCount > 16 || ...
        any(parameterIds == 0) || any(~isfinite(parameterValues))
    error("iiw:preprocessing:InvalidTransformParameters", ...
        "Transformation parameters are incomplete or invalid.");
end

entry.order = order;
entry.operationCode = operationCode;
entry.parameterIds(1:parameterCount) = parameterIds;
entry.parameterValues(1:parameterCount) = parameterValues;
entry.parameterCount = uint8(parameterCount);
entry.implementationVersion = implementationVersion;
entry.configurationVersion = configurationVersion;
entry.inputReference = inputReference;
entry.outputReference = outputReference;
end

function entry = emptyEntry()
entry = struct( ...
    "order", uint8(0), ...
    "operationCode", uint8(0), ...
    "parameterIds", zeros(16, 1, "uint16"), ...
    "parameterValues", zeros(16, 1, "single"), ...
    "parameterCount", uint8(0), ...
    "implementationVersion", uint16(0), ...
    "configurationVersion", uint16(0), ...
    "inputReference", uint32(0), ...
    "outputReference", uint32(0));
end

function valid = validScalar(value, expectedClass, allowZero)
valid = isa(value, expectedClass) && isscalar(value) && isreal(value);
if valid && ~allowZero
    valid = value ~= 0;
end
end
