function result = run_intelligent_workflow_integration(repositoryRoot, options)
%RUN_INTELLIGENT_WORKFLOW_INTEGRATION Execute the accepted intelligent core end to end.
% Demonstration only: this function produces advisory outputs and no mission,
% actuator, approval-command, or safety-command output.

arguments
    repositoryRoot (1,1) string
    options.RejectQuality (1,1) logical = false
    options.Approved (1,1) logical = true
end

fixturePath = fullfile(repositoryRoot,"tests","intelligent-inspection", ...
    "fixtures","quality_contract_fixtures.mat");
fixture = load(fixturePath);
image = fixture.nominalImage;
if options.RejectQuality
    image = fixture.darkImage;
end

quality = iiw.quality.validateInspectionData( ...
    fixture.inspectionData,fixture.inspectionMetadata,image,fixture.configuration);

preprocessConfiguration = struct( ...
    "processedItemId",uint32(501), ...
    "representationRef",uint32(601), ...
    "transformRecordRef",uint32(701), ...
    "configurationVersion",uint16(1), ...
    "schemaVersion",uint16(1), ...
    "implementationVersion",uint16(1), ...
    "intermediateReferenceBase",uint32(800), ...
    "operationOrder",uint8([1 2]), ...
    "targetChannels",uint8(1), ...
    "targetSize",uint32([32;32]), ...
    "interpolationMethod",uint8(2), ...
    "intensityInputRange",single([0;1]), ...
    "intensityOutputRange",single([0;1]), ...
    "denoiseSigma",single(0), ...
    "denoiseFilterSize",uint8(3), ...
    "contrastInputRange",single([0;1]), ...
    "contrastOutputRange",single([0;1]), ...
    "contrastGamma",single(1));

[processedData,processedImage,transformHistory] = ...
    iiw.preprocessing.preprocessInspectionData( ...
    fixture.inspectionData,quality,image,preprocessConfiguration);

detector = iiw.detection.DetectorContract.create( ...
    @iiw.detection.conventionalDetector,uint32(501),uint16(1));
detectionConfiguration = struct( ...
    "resultId",uint32(901), ...
    "labelId",uint8(1), ...
    "resultSchemaVersion",uint16(1), ...
    "minimumConfidence",single(0.50), ...
    "detectionMode",uint8(2), ...
    "intensityThreshold",single(0.40), ...
    "minimumArea",uint32(4), ...
    "smoothingSigma",single(0), ...
    "emitLocation",true, ...
    "locationScale",double([1;1]), ...
    "locationOrigin",double([0;0;0]), ...
    "frameId",uint16(1));

if isempty(processedImage)
    detection = iiw.detection.DetectorContract.invalidResult();
    detectionStatus = uint8(3);
else
    [detection,detectionStatus] = iiw.detection.runDetector( ...
        processedData,processedImage,detector,detectionConfiguration);
end

featureConfiguration = struct( ...
    "featureSetId",uint32(1001), ...
    "detectionSchemaVersion",uint16(1), ...
    "featureSchemaVersion",uint16(1), ...
    "catalogVersion",uint16(1), ...
    "extractorVersion",uint16(1));
features = iiw.features.extractNumericalFeatures(detection,featureConfiguration);
featuresValid = iiw.features.validateFeatureSet(features);

predictor = iiw.prediction.PredictorContract( ...
    uint32(1101),uint16(1),uint16(1),uint16(1),uint16((1:6).'), ...
    @(~) struct("estimate",single(72),"uncertainty",single(0.10), ...
    "outOfDistribution",false));
predictionConfiguration = struct( ...
    "predictionId",uint32(1201), ...
    "contextOrHorizon",uint32(7), ...
    "schemaVersion",uint16(1), ...
    "maximumUncertainty",single(0.20), ...
    "allowedModelVersions",uint16(1));

if featuresValid && features.featureSetId ~= 0
    prediction = iiw.prediction.predictHealth( ...
        features,predictor,predictionConfiguration);
else
    prediction = iiw.prediction.predictHealth( ...
        features,predictor,predictionConfiguration);
end

references = zeros(16,1,"uint32");
references(1) = uint32(1201);
riskEvidence = struct( ...
    "assessmentId",uint32(1301), ...
    "evidenceRefs",references, ...
    "referenceCount",uint8(1), ...
    "qualitySupplied",true, ...
    "qualityAccepted",quality.status == uint8(1), ...
    "detectionSupplied",detectionStatus <= uint8(2), ...
    "detectionConfidence",single(detection.confidence), ...
    "detectionConfidenceValid",logical(detection.confidenceValid), ...
    "internalAssessmentFailure",false);
riskPolicy = struct( ...
    "policyVersion",uint16(1), ...
    "maximumUncertainty",single(0.20), ...
    "minimumConfidence",single(0.80), ...
    "mediumHealthThreshold",single(50), ...
    "lowHealthThreshold",single(80));
risk = iiw.risk.assessRisk(prediction,riskEvidence,riskPolicy);

approvalRequest = makeApprovalRequest(risk.assessmentId);
approvalDecision = makeApprovalDecision(options.Approved);
approvalContext = makeApprovalContext();
approvalPolicy = struct( ...
    "policyVersion",uint16(1), ...
    "decisionVersion",uint16(1), ...
    "waitingTimeoutMs",uint64(300000), ...
    "approvalValidityMs",uint64(900000), ...
    "authorizedRoles",uint8([1;2;3]), ...
    "delegationEnabled",true);
approval = iiw.approval.evaluateApproval( ...
    approvalRequest,approvalDecision,approvalContext,approvalPolicy);

recommendation = struct( ...
    "code",uint8(0), ...
    "advisoryOnly",true, ...
    "forwardingEligible",approval.forwardingEligible);
if approval.forwardingEligible
    if risk.riskLevel == uint8(3)
        recommendation.code = uint8(3);
    elseif risk.riskLevel == uint8(2)
        recommendation.code = uint8(2);
    elseif risk.riskLevel == uint8(1)
        recommendation.code = uint8(1);
    end
end

[evidenceResults,storedRecords] = recordStageEvidence();
evidencePolicy = struct("policyVersion",uint16(1), ...
    "schemaVersion",uint16(1),"defaultRetentionDays",uint16(365));
chain = iiw.evidence.validateEvidenceChain(storedRecords,evidencePolicy);

result = struct( ...
    "quality",quality, ...
    "processedData",processedData, ...
    "processedImage",processedImage, ...
    "transformHistory",transformHistory, ...
    "detection",detection, ...
    "detectionStatus",detectionStatus, ...
    "features",features, ...
    "featuresValid",featuresValid, ...
    "prediction",prediction, ...
    "risk",risk, ...
    "approval",approval, ...
    "recommendation",recommendation, ...
    "evidenceResults",evidenceResults, ...
    "evidenceChain",chain, ...
    "phase7DeepLearningEnabled",false, ...
    "missionSupervisorConnected",false, ...
    "demonstrationOnly",true);
end

function request = makeApprovalRequest(assessmentId)
refs=zeros(16,1,"uint32"); refs(1)=uint32(1301);
request=struct("requestId",uint32(10),"assessmentId",assessmentId, ...
    "proposedRecommendation",uint32(20),"evidenceRefs",refs, ...
    "requestedAt",uint64(1000000),"expiresAt",uint64(4000000), ...
    "policyVersion",uint16(1),"referenceCount",uint8(1));
end

function decision = makeApprovalDecision(approved)
code=uint8(2);
if approved, code=uint8(1); end
decision=struct("requestId",uint32(10),"decision",code, ...
    "decidedBy",uint32(80),"decidedAt",uint64(1100000), ...
    "comments",uint32(0),"decisionVersion",uint16(1));
end

function context = makeApprovalContext()
context=struct("requestPresent",true,"decisionPresent",true, ...
    "recommendationId",uint32(20),"requesterId",uint32(60), ...
    "approverRole",uint8(1),"evaluationTimestamp",uint64(1200000), ...
    "delegationActive",false,"delegationDepth",uint8(0), ...
    "delegatorId",uint32(0),"originalApproverId",uint32(0), ...
    "escalationRequested",false,"externalSafetyActive",false, ...
    "externalSafetyAuthenticated",false,"internalEvaluationFailure",false);
end

function [results,records] = recordStageEvidence()
policy=struct("policyVersion",uint16(1),"schemaVersion",uint16(1), ...
    "defaultRetentionDays",uint16(365));
writer=makeWriter();
records=[];
results=repmat(struct(),0,1);
for stage=1:9
    record=baseEvidenceRecord(stage);
    if stage>1
        record.inputEvidenceRefs(1)=uint32(stage-1);
        record.inputReferenceCount=uint8(1);
    end
    [one,stored]=iiw.evidence.recordEvidence( ...
        record,writer,uint8(1),policy);
    results(stage,1)=one; %#ok<AGROW>
    records=[records stored]; %#ok<AGROW>
end
end

function record = baseEvidenceRecord(stage)
record=struct( ...
    "recordId",uint32(stage),"transactionId",uint32(1601), ...
    "stageId",uint32(stage),"actorOrComponent",uint32(101), ...
    "inputEvidenceRefs",zeros(16,1,"uint32"), ...
    "inputReferenceCount",uint8(0), ...
    "outputArtifactRef",uint32(2000+stage), ...
    "dataVersions",[uint16(1);zeros(15,1,"uint16")], ...
    "dataVersionCount",uint8(1), ...
    "modelVersions",[uint16(1);zeros(15,1,"uint16")], ...
    "modelVersionCount",uint8(1), ...
    "configurationVersions",[uint16(1);zeros(15,1,"uint16")], ...
    "configurationVersionCount",uint8(1), ...
    "softwareVersion",uint16(1),"timestamp",uint64(1770000000000+stage), ...
    "outcome",uint8(1),"failureStatus",uint8(0), ...
    "policyVersion",uint16(1),"schemaVersion",uint16(1), ...
    "retentionDays",uint16(365),"retentionHold",false);
end

function writer = makeWriter()
ids=zeros(1,0,"uint32");
writer=@append;
    function ok=append(record)
        ok=~any(ids==record.recordId);
        if ok, ids(end+1)=record.recordId; end
    end
end
